# Generated by Django 4.0.5 on 2022-06-27 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='exercise',
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.ForeignKey(default='4', on_delete=django.db.models.deletion.CASCADE, to='gym.equipment'),
            preserve_default=False,
        ),
    ]
