# Generated by Django 4.0.5 on 2022-07-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_routine_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='day',
            field=models.DateField(choices=[('l', 'lunes'), ('m', 'martes'), ('x', 'miercoles'), ('j', 'jueves'), ('v', 'viernes')]),
        ),
    ]
